### ISSUE TITLE
[USERSNAP] Restore Votes does not upate My Votes

### ISSUE THREAD

**Issue by dmtrjsg** [Joystream/pioneer#2991]
**Taken at**: https://dao.joystream.org/#/election
**Fields**:
- Houston, we have a problem.: Restore Votes does not upate My Votes
- Comment: The votes are restored from file but user has to reload the page manually.
- Feedback: l1dev

![SCREENSHOT](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/759150c8-afab-41b0-beaf-601fec21dc72-annotated_10120d69-d1c1-4a70-82fa-ef277bdb9f46.png?etag=7260a90a9eebc7d874b4db3082f1543b)
*[Download original image](https://resources.usersnap.com/company/f9f719df-a929-4461-bb6e-46dbfbceffb7/datapoint_screenshot/759150c8-afab-41b0-beaf-601fec21dc72-annotated_10120d69-d1c1-4a70-82fa-ef277bdb9f46.png?etag=7260a90a9eebc7d874b4db3082f1543b)*

**Browser**: Chrome 100 (Linux)
**Screen size**: 1920x1080
**Browser size**: 1190x1216
**[Open #242 in Usersnap](https://app.usersnap.com/l/feedback/4f1936ef-9048-44cb-b924-bea7a523d7d4?utm_medium=integration&utm_campaign=integration&utm_content=open)**

Powered by **[Usersnap](https://usersnap.com/?utm_source=product&amp;utm_medium=poweredbylink&amp;utm_campaign=github_entry)**.

**Comment by dmtrjsg** [comment]
Probably must be addressed in #2311. To be triaged.

**Comment by ivanturlakov** [comment]
Tested on https://dao-git-carthage-joystream.vercel.app/#/election
wss://54.227.116.57.nip.io/ws-rpc

@traumschule @dmtrjsg  Looks like not fixed yet

⚠️ The votes are restored from file but user has to reload the page manually. Tested on Voting and Revealing stages.

To test this case, I voted for a few candidates then backup votes, and then deleted votes from Local Storage.

**Comment by traumschule** [comment]
There's a fix in #3868 by @mkbeefcake.
